### ISSUE TITLE
Are there any requirements regarding attribution?

### ISSUE THREAD

**Issue by abhijitvalluri** [Alobar/AndroidPreferenceTest#1]
Hi,

Thanks for the NumberPickerPreference code. I am using it in an app I have developed, which is live in Google Play Store. Is there any requirements regarding providing attribution for using your code?

**Comment by robmeeuwisse** [comment]
Hi, It's great to hear you are using the NumberPickerPreference. I wish you the best of luck with your app and hope it grows big.

The code is published under the [MIT license](https://github.com/Alobar/AndroidPreferenceTest/blob/master/LICENSE) which states: "The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software." That means you should reproduce the text from the linked file somewhere in your app. You may do that however is convenient for you. For example, the Google Maps app has an Open Source Licenses page in Settings.

**Comment by abhijitvalluri** [comment]
Thank you! I will soon add this info to the app (but currently cannot
continue work on it due to limitations from work. Just started a job!)

Regards,
Abhijit
