### ISSUE TITLE
Updating summary

### ISSUE THREAD

**Issue by BlueBeardo** [Alobar/AndroidPreferenceTest#2]
How do I get the summary to show and update in the custom preference? I tried adding

``` Java
public boolean onPreferenceChange(Preference preference, Object value) {
...
else if(preference instanceof com.example.preference.NumberPickerPreference){
    preference.setSummary("Test");
}
...
}
```

But it won't add or update the summary. Can you shed some light on what I'm doing wrong?

**Comment by robmeeuwisse** [comment]
Setting the summary works exactly the same with custom preferences. 

I have updated the project to demonstrate the use of `setSummary()`. Preference 'Give me a number' now shows the current value in the summary. Just like you, I update the summary in the `onPreferenceChange` handler: [see here](https://github.com/Alobar/AndroidPreferenceTest/blob/master/app/src/main/java/alobar/preferencetest/MyPreferenceFragment.java#L68) .

You will have to debug your code to find out why the summary is not set in your case. Does the line `preference.setSummary("Test");` actually get executed? Put a breakpoint on it to check.

**Comment by BlueBeardo** [comment]
That worked. Thanks for adding that. I ended up doing all the classes close to yours. I was having trouble with the boilerplate code AndroidStudio puts out when you have it create a settings class.

**Comment by robmeeuwisse** [comment]
Happy to help.
